# **Background information:**

numpy is a multi dimensional array


---


reasons why numpy array is better than List:

1.  numpy uses fixed type
2.  numpy takes less space for each data
3.  numpy does not have type checking. type is determined at initialization
4.  numpy uses contiguous memory(not list). This enables SIMD Vector processing. this also enables cache utilizetion



---


axix = 0 means column
axis = 1 means row






# import library

In [72]:
import numpy as np

# Initialize numpy array





dtype is an optional parametter. it can be used to set the datatype of the array. especially, the type int16 can be used to reduce the size of array as the default value for dtype is int64




---



List of function:




* np.array()
* np.zeros()
* np.ones()
* np.full()
* np.full_like()
* np.random.rand()
* np.random.randint()
* np.identity()
* np.repeat()








In [73]:
#Initializing by hand
print("#Initializing by hand")
a = np.array([1,2,3,4] , dtype = "int16")
b = np.array([[1,2,3,4] , [5,6,7,8] ])
print(a)
print(b)

print("\n\n\n")








#initialize all element by zero
print("initialize all element by zero")
a = np.zeros((2,3), dtype = "int16") # dimension 2x3
print(a)

print("\n\n\n")









#initialize all element by 1
print("#initialize all element by 1")
a = np.ones((2,3) , dtype = "int16") # dimension 2x3
print(a)

print("\n\n\n")









#initialize all element by 99
print("initialize all element by 99")
a = np.full((2,3), 99, dtype = "int16" ) # dimension 2x3
print(a)

print("\n\n\n")










#initialize all element by 99 and dimension will be similar to the array b
print("initialize all element by 99 and dimension will be similar to the array b")
b = np.array([1,2,3,4])
a = np.full_like(b,99)
print("b:",b)
print("a:",a)

print("\n\n\n")









#initialize all element by random element between 0 to 1
print("initialize all element by random element between 0 to 1")
a = np.random.rand(2,3) # dimension 2x3
print(a)

print("\n\n\n")
















#initialize all element by random element between 2 to 7
print("initialize all element by random element between 2 to 7")
a = np.random.randint(2,7, size=(2,3)) # dimension 2x3
print(a)

print("\n\n\n")














#Identitly matrix of size 5
print("Identitly matrix of size 5")
a = np.identity(5) # dimension 5x5
print(a)

print("\n\n\n")

















#new array called a that was crereated by repeating b three times
print("new array called a that was crereated by repeating b three times")
b = np.array([1,2,3,4])
a = np.repeat(b, 3) # dimension 2x3
print("b:",b)
print("a:",a)

print("\n\n\n")























#Initializing by hand
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]




initialize all element by zero
[[0 0 0]
 [0 0 0]]




#initialize all element by 1
[[1 1 1]
 [1 1 1]]




initialize all element by 99
[[99 99 99]
 [99 99 99]]




initialize all element by 99 and dimension will be similar to the array b
b: [1 2 3 4]
a: [99 99 99 99]




initialize all element by random element between 0 to 1
[[0.10196286 0.5175748  0.9993582 ]
 [0.26260512 0.14788495 0.04902352]]




initialize all element by random element between 2 to 7
[[2 2 4]
 [6 5 3]]




Identitly matrix of size 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]




new array called a that was crereated by repeating b three times
b: [1 2 3 4]
a: [1 1 1 2 2 2 3 3 3 4 4 4]






# Finding Dimension and shape

In [74]:
a = np.array([1,2,3,4] , dtype = "int16")
b = np.array([[1,2,3,4] , [5,6,7,8] ])

print("Dimension for a:",   a.ndim)
print("Dimension for b:",   b.ndim)
print("Shape for a:",  a.shape)
print("shape for b:",   b.shape)

Dimension for a: 1
Dimension for b: 2
Shape for a: (4,)
shape for b: (2, 4)


# Finding datatype, element size and total size

In [75]:
a = np.array([1,2,3,4] , dtype = "int16")
b = np.array([[1,2,3,4] , [5,6,7,8] ])

print("DataType for a:",   a.dtype)
print("DataType for b:",b.dtype)
print("Size of each element for a (bytes):",   a.itemsize)
print("Size of each element for b (bytes):",   b.itemsize)
print("Total size for a (bytes):",  a.nbytes)
print("Total size for b (bytes):",   b.nbytes)

DataType for a: int16
DataType for b: int64
Size of each element for a (bytes): 2
Size of each element for b (bytes): 8
Total size for a (bytes): 8
Total size for b (bytes): 64


# Changing Data Type

In [76]:
a = np.array([1,2,3,4] , dtype = "int16")
print("Previous Type: ",a.dtype)
a = a.astype("float")
print("New Type: ",a.dtype)

Previous Type:  int16
New Type:  float64


# Accessing numpy array
List splicing logic can be used here

one dimensional array

In [77]:
a = np.array([1,2,3,4])
print(a)




#Accessing one element
print("")
print(a[3])




#Accessing multiple element (From second element to fourth element)
print("")
print(a[1:4])

[1 2 3 4]

4

[2 3 4]


Multi-Dimensional array

In [78]:
a = np.array([[1,2,3,4,5,6,7,8],  [ 3,4,5,6,7,8,9,7], [11,22,33,44,55,66,77,88]  ])
print(a ,end = "\n\n\n")




#Accesssing element of row 1 column 5 (Assuming row and columns starts from 0)
print("Accesssing element of row 1 column 5 (Assuming row and columns starts from 0)")
print(a[1,5]  ,end = "\n\n\n" )




#Getting specific row . row 0 (Assuming row and columns starts from 0)
print("Getting specific row . row 0 (Assuming row and columns starts from 0)")
print(a[0,:],end = "\n\n\n")




#Getting specific column . column 4 (Assuming row and columns starts from 0)
print("Getting specific column . column 4 (Assuming row and columns starts from 0)")
print(a[:,4],end = "\n\n\n")






"""" Accessing the chunk that was * icon with it
[[ 1  2  3  4  5  6  7  8]
 [ 3  4  5  6*  7*  8  9  7]
 [11 22 33 44* 55* 66 77 88]]
"""
print("Accesssing element of row 1 column 5 (Assuming row and columns starts from 0)")
print(a[ 1:3 ,3:5],end = "\n\n\n")



[[ 1  2  3  4  5  6  7  8]
 [ 3  4  5  6  7  8  9  7]
 [11 22 33 44 55 66 77 88]]


Accesssing element of row 1 column 5 (Assuming row and columns starts from 0)
8


Getting specific row . row 0 (Assuming row and columns starts from 0)
[1 2 3 4 5 6 7 8]


Getting specific column . column 4 (Assuming row and columns starts from 0)
[ 5  7 55]


Accesssing element of row 1 column 5 (Assuming row and columns starts from 0)
[[ 6  7]
 [44 55]]




# Changing rows and columns of numpy array

In [79]:
a = np.array([[1,2,3,4,5,6,7,8], [ 3,4,5,6,7,8,9,7], [11,22,33,44,55,66,77,88]])
print(a ,end="\n\n\n" )




#changing the entire column 2 to 99 (Assuming row and columns starts from 0)
a[:, 2] = 99
print( "changing the entire column 2 to 99 (Assuming row and columns starts from 0)")
print(a,end="\n\n\n" )





#changing the entire row 0 to 99 (Assuming row and columns starts from 0)
a[0, :] = 99
print("changing the entire row 0 to 99 (Assuming row and columns starts from 0)")
print(a,end="\n\n\n" )






#changing column 6 to [123,234,345] (Assuming row and columns starts from 0)
a[:, 6] =[123,234,345]
print("changing column 6 to [123,234,345] (Assuming row and columns starts from 0)")
print(a,end="\n\n\n" )


[[ 1  2  3  4  5  6  7  8]
 [ 3  4  5  6  7  8  9  7]
 [11 22 33 44 55 66 77 88]]


changing the entire column 2 to 99 (Assuming row and columns starts from 0)
[[ 1  2 99  4  5  6  7  8]
 [ 3  4 99  6  7  8  9  7]
 [11 22 99 44 55 66 77 88]]


changing the entire row 0 to 99 (Assuming row and columns starts from 0)
[[99 99 99 99 99 99 99 99]
 [ 3  4 99  6  7  8  9  7]
 [11 22 99 44 55 66 77 88]]


changing column 6 to [123,234,345] (Assuming row and columns starts from 0)
[[ 99  99  99  99  99  99 123  99]
 [  3   4  99   6   7   8 234   7]
 [ 11  22  99  44  55  66 345  88]]




# Basic mathematics with numpy


In [80]:
# adding 2 to the whole array
print("adding 2 to the whole array")
a = np.array([1,2,3,4])
print("Original array:",a)
a = a + 2
print("Output array: " ,a)

print("\n\n\n")














# subtracting 2 to the whole array
print("subtracting 2 to the whole array")
a = np.array([1,2,3,4])
print("Original array:",a)
a = a - 2
print("Output array: " ,a)

print("\n\n\n")















# multiplicating 2 to the whole array
print("multiplicating 2 to the whole array")
a = np.array([1,2,3,4])
print("Original array:",a)
a = a * 2
print("Output array: " ,a)

print("\n\n\n")













# dividing 2 to the whole array
print("dividing 2 to the whole array")
a = np.array([1,2,3,4])
print("Original array:",a)
a = a / 2
print("Output array: " ,a)

print("\n\n\n")














# sine (cos, tan , sinh, etc can be done in the same way)
print("sine (cos, tan , sinh, etc can be done in the same way)")
a = np.array([1,2,3,4])
print("Original array:",a)
a = np.sin(a)
print("Output array: " ,a)

print("\n\n\n")












# Adding one array with another array
# adding array a with array b (other operations can be done in the same way)
print("adding array a with array b (other operations can be done in the same way)")
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print("Original array a:",a)
print("Original array b:",b)
c = a+b
print("Output array: " ,c)

print("\n\n\n")




adding 2 to the whole array
Original array: [1 2 3 4]
Output array:  [3 4 5 6]




subtracting 2 to the whole array
Original array: [1 2 3 4]
Output array:  [-1  0  1  2]




multiplicating 2 to the whole array
Original array: [1 2 3 4]
Output array:  [2 4 6 8]




dividing 2 to the whole array
Original array: [1 2 3 4]
Output array:  [0.5 1.  1.5 2. ]




sine (cos, tan , sinh, etc can be done in the same way)
Original array: [1 2 3 4]
Output array:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]




adding array a with array b (other operations can be done in the same way)
Original array a: [1 2 3 4]
Original array b: [2 3 4 5]
Output array:  [3 5 7 9]






# Linear Algebra



---

functions used:
* np.matmul()
* np.linalg.det()

In [81]:
#matrix multiplication
a = np.ones((2,3))
print("Matrix a: \n", a)
b = np.random.randint(1,10, size = (3,2))
print("Matrix b: \n",b)

c = np.matmul(a,b)
print("Matrix multiplication of a and b: \n",c)

print("\n\n\n")












#determinant of matrix
print("determinant of matrix")
a = np.random.randint(1,10, size = (3,3))
print("Matrix a: \n",a)
b = np.linalg.det(a)
print("Determinant of matrix a: \n",b)

print("\n\n\n")



Matrix a: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Matrix b: 
 [[8 2]
 [9 4]
 [2 8]]
Matrix multiplication of a and b: 
 [[19. 14.]
 [19. 14.]]




determinant of matrix
Matrix a: 
 [[4 8 6]
 [6 7 6]
 [7 8 3]]
Determinant of matrix a: 
 78.0






# Statistics


Functions Used:
* np.min()

In [82]:
#minimum value of entire array
print("minimum value of entire array")
a = np.random.randint(1,10, size=(2,3))
print("Matrix a: \n",a)
b = np.min(a)
print("Minimum value of matrix a: ",b)

print("\n\n\n\n")













#minimum value from rows
print("minimum value from rows")
print("Matrix a: \n",a)
b = np.min(a, axis = 1)
print("Minimum value of matrix a: \n",b)

print("\n\n\n\n")




















#minimum value from columns
print("minimum value from cplumns")
print("Matrix a: \n",a)
b = np.min(a, axis = 0)
print("Minimum value of matrix a: \n",b)

print("\n\n\n\n")



minimum value of entire array
Matrix a: 
 [[7 5 4]
 [3 2 7]]
Minimum value of matrix a:  2





minimum value from rows
Matrix a: 
 [[7 5 4]
 [3 2 7]]
Minimum value of matrix a: 
 [4 2]





minimum value from cplumns
Matrix a: 
 [[7 5 4]
 [3 2 7]]
Minimum value of matrix a: 
 [3 2 4]







# Reorganize Array ( Resize, row and column concat)


Functions Used:
* array.reshape()
* np.vstack()
* np.hstack()

resize

In [83]:
#Reshape Array (For reshape just have to make sure number of element remains same after reshape)
print("")
a = np.random.randint(1,10,size= (3,4))
print("Original Array: \n",a)

print("\n\n\n")






#reshape by 1x12
print("reshape by 1x12")
b = a.reshape((1,12))
print("output: \n" ,b)

print("\n\n\n")









#reshape by 12x1
print("reshape by 12x1")
c = a.reshape((12,1))
print("output: \n" ,c)

print("\n\n\n")













#reshape by 6x2
print("reshape by 6x2")
d = a.reshape((6,2))
print("output: \n" ,d)



print("\n\n\n\n\n\n\n\n\n")


Original Array: 
 [[4 8 5 7]
 [3 8 1 7]
 [8 2 6 6]]




reshape by 1x12
output: 
 [[4 8 5 7 3 8 1 7 8 2 6 6]]




reshape by 12x1
output: 
 [[4]
 [8]
 [5]
 [7]
 [3]
 [8]
 [1]
 [7]
 [8]
 [2]
 [6]
 [6]]




reshape by 6x2
output: 
 [[4 8]
 [5 7]
 [3 8]
 [1 7]
 [8 2]
 [6 6]]












vstack

In [84]:
#concatenating rows of array b on array a
print("concatenating rows of array b on array a ")
a = np.random.randint(1,10 , size = (2,2))
b = np.random.randint(1,10 , size = (2,2))
print("Matrix a: \n" ,a)
print("Matrix b: \n" ,b)

a = np.vstack([a,b])
print("Array a after Concatenation: \n",a)

print("\n\n\n\n")














#concatenating columns of array b on array a
print("concatenating columns of array b on array a")
a = np.random.randint(1,10 , size = (2,2))
b = np.random.randint(1,10 , size = (2,2))
print("Matrix a: \n" ,a)
print("Matrix b: \n" ,b)

a = np.hstack((a,b))
print("Array a after Concatenation: \n",a)

print("\n"*8)

concatenating rows of array b on array a 
Matrix a: 
 [[6 6]
 [4 3]]
Matrix b: 
 [[7 4]
 [5 3]]
Array a after Concatenation: 
 [[6 6]
 [4 3]
 [7 4]
 [5 3]]





concatenating columns of array b on array a
Matrix a: 
 [[2 9]
 [3 5]]
Matrix b: 
 [[1 5]
 [4 5]]
Array a after Concatenation: 
 [[2 9 1 5]
 [3 5 4 5]]











# Load Data From Files




np.genfromtxt() :  first parameter is filename. delimeter parameter is used to know how is the data organized. if the datas are separated by comma, then the value of delimiter = ",".  Works like the split function


on defaults the data type of using this function is float


---

function used:
* np.genfromtxt()

In [ ]:
a = np.genfromtxt("data.txt", delimiter = ",")

# Boolean mask and filtering using boolean mask


Funcion Used:
* np.any()
* np.all()

In [86]:
#boolean mask for all number greater than 5
print("boolean mask for all number greater than 5")
a = np.random.randint(1,10 , size=(1,20))
print("Matrix: \n",a)

mask = a > 5
print("Boolen Mask: \n", mask)

print("\n"*4)








#Filtering Using Boolean Mask (filtering by if number is greater than 5)
print("Filtering Using Boolean Mask (filtering by if number is greater than 5)")
filtered_data = a[mask]
print("Filtered Array: \n",filtered_data)

print("\n"*4)















#shortHand for filtering (filtering by if number is greater than 5)
print("#shortHand for filtering (filtering by if number is greater than 5)")
a = a[ a>5 ]
print(a)

print("\n"*10)

boolean mask for all number greater than 5
Matrix: 
 [[6 2 8 2 7 2 8 1 8 5 3 1 9 7 9 8 9 6 5 4]]
Boolen Mask: 
 [[ True False  True False  True False  True False  True False False False
   True  True  True  True  True  True False False]]





Filtering Using Boolean Mask (filtering by if number is greater than 5)
Filtered Array: 
 [6 8 7 8 8 9 7 9 8 9 6]





#shortHand for filtering (filtering by if number is greater than 5)
[6 8 7 8 8 9 7 9 8 9 6]













boolean mask for rows and culumns

In [87]:
a = np.random.randint(1,10 , size= (3,10))
print("Array: \n",a)

print("\n"*4)








#boolean mask for rows (any)(will have true if any value is greater than 5 in rows)
print("boolean mask for rows (any)(will have true if any value is greater than 5 in rows)")
mask = np.any( a > 5  , axis = 1  )
print(mask)

print("\n"*4)












#boolean mask for columns(any)   (will have true if any value is greater than 5 in columns)
print("boolean mask for columns(any)   (will have true if any value is greater than 5 in columns)")
mask = np.any( a > 5  , axis = 0  )
print(mask)

print("\n"*4)












#boolean mask for rows (all)(will have true if all value of a row is greater than 5 in rows)
print("boolean mask for rows (all)(will have true if all value of a row is greater than 5 in rows)")
mask = np.all( a > 5  , axis = 1  )
print(mask)

print("\n"*4)













#boolean mask for rows (all)(will have true if all value of a column is greater than 5 in columns)
print("boolean mask for rows (all)(will have true if all value of a column is greater than 5 in columns)")
mask = np.all( a > 5  , axis = 0  )
print(mask)

print("\n"*4)

Array: 
 [[6 1 1 3 9 2 5 6 7 5]
 [7 9 9 9 7 3 8 5 4 5]
 [7 7 4 1 2 9 2 4 5 9]]





boolean mask for rows (any)(will have true if any value is greater than 5 in rows)
[ True  True  True]





boolean mask for columns(any)   (will have true if any value is greater than 5 in columns)
[ True  True  True  True  True  True  True  True  True  True]





boolean mask for rows (all)(will have true if all value of a row is greater than 5 in rows)
[False False False]





boolean mask for rows (all)(will have true if all value of a column is greater than 5 in columns)
[ True False False False False False False False False False]





